language: php
sudo: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

matrix:
  allow_failures:
    - php: hhvm-3.12
    - php: nightly
  fast_finish: true
  include:
    - php: hhvm-3.12
      dist: trusty

before_install:
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi

install:
  - composer install --no-interaction
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
  - mkdir -p build/logs
  - ls -al

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php coveralls.phar -v

cache:
  directories:
  - vendor
  - $HOME/.cache/composer
